[[constraint]]
  branch = "master"
  name = "github.com/PagerDuty/godspeed"

[[constraint]]
  name = "github.com/go-chi/chi"
  version = "3.3.1"

[[constraint]]
  name = "github.com/gorilla/context"
  version = "1.1.0"

[[constraint]]
  name = "github.com/gorilla/mux"
  version = "1.6.0"

[[constraint]]
  name = "github.com/stretchr/testify"
  version = "1.1.4"
